### ISSUE TITLE
GitLab CI/CDで特定のファイルが変更された場合にのみジョブを実行する

### ISSUE THREAD

**Issue by kenriki** [kenriki/swagger_sample#1]
GitLab 11.4から only:changes という記法がサポートされました．これにより，特定のファイルが変更された場合のみジョブを実行できます．

例
以下のように記述すると，ブランチをpushした時に terraform/ フォルダのファイルが変更されている場合にのみジョブが実行されます．

```
stages:
  - build

terraform_plan:
  stage: build
  only:
    changes:
      - terraform/**/*
      - .gitlab-ci.yml
  image:
    name: hashicorp/terraform:0.12.8
    entrypoint:
      - /usr/bin/env
  script:
    - cd terraform/
    - terraform --version
    - terraform init
    - terraform validate
    - terraform plan -out=plan.tfplan
  artifacts:
    name: plan
    paths:
      - terraform/plan.tfplan
  tags:
    - terraform
```

`only`  はブランチ名と組み合わせることも可能です．以下のように記述すると，先ほどの条件に加えて，masterブランチに対してのみジョブが実行されます．

```
only:
    changes:
      - terraform/**/*
      - .gitlab-ci.yml
    refs:
      - master
```

# 注意
`.gitlab-ci.yml ` を変更した場合は何らかの副作用がある場合が多い

# 参考リンク

https://docs.gitlab.com/ee/ci/yaml/#onlychangesexceptchanges

https://docs.gitlab.com/ee/ci/yaml/#artifacts

https://engineering.linecorp.com/ja/blog/creating-api-documents-with-swagger/

https://www.google.com/amp/s/blog.kyanny.me/entry/2020/08/06/012807%3famp=1

https://int128.hatenablog.com/entry/2019/09/11/192310
